name: Build Submit Android Eas Expo

on:
  release:
    types: [published]

jobs:
  build_submit_android:
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ”¨ Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: ğŸ”§ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸš€ Create eas production build and submit to play store
        run: pnpm eas build --platform android --profile production
